# Generated by Django 3.1.5 on 2021-01-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cafe_mainphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='modifiedDate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='publishedDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
