# Generated by Django 3.1.5 on 2021-01-15 06:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210115_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='modifiedDate',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='publishedDate',
        ),
        migrations.AddField(
            model_name='cafe',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
