# Generated by Django 3.1.5 on 2021-01-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210115_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='lng',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='location',
            field=models.CharField(choices=[('Hangyeong-myeon', '한경면'), ('Hallim-eup', '한림읍'), ('Aewol-eup', '애월읍'), ('Jeju-si', '제주시'), ('Jocheon-eup', '조천읍'), ('Gujwa-eup', '구좌읍'), ('Udo-myeon', '우도면'), ('Seongsan-eup', '성산읍'), ('Pyoseon-myeon', '표선면'), ('Namwon-eup', '남원읍'), ('Seogwipo-si', '서귀포시'), ('Andeok-myeon', '안덕면'), ('Daejeong-eup', '대정읍')], max_length=50),
        ),
    ]
