# Generated by Django 3.1.5 on 2021-01-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210115_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='subphoto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
