# Generated by Django 3.1.5 on 2021-01-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_cafe_subphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='insta',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='phone',
            field=models.TextField(null=True),
        ),
    ]
