# Generated by Django 3.1.5 on 2021-01-16 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210116_2125'),
        ('main', '0013_auto_20210116_0028'),
    ]

    operations = [
    ]
